name: Cypress E2E Tests (Multi-Browser + Allure)


on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    name: Cypress E2E on ${{ matrix.browser }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        browser: [chrome, firefox, electron]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Prepare allure results folder
        run: rm -rf allure-results && mkdir allure-results

      - name: Run Cypress tests on ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          install: true
          command: npx cypress run
        env:
          username: ${{ secrets.CYPRESS_USERNAME }}
          password: ${{ secrets.CYPRESS_PASSWORD }}
          tags: $${{ TAGS }}

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results/

  merge-allure:
    name: Merge and Publish Allure Report
    runs-on: ubuntu-latest
    needs: run-tests
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure result artifacts
        uses: actions/download-artifact@v3
        with:
          path: merged-allure-results

      - name: Merge Allure results
        run: |
          mkdir -p allure-results
          find merged-allure-results -type f -name "*.json" -exec cp {} allure-results/ \;

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./allure-report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          destination_dir: |
            ${{ github.event_name == 'schedule' && 'nightly/allure-report' ||
                github.event_name == 'pull_request' && format('pr-{0}/allure-report', github.event.pull_request.number) ||
                'push/allure-report' }}

       - name: Comment PR with Allure report link
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Allure Report (Multi-Browser) is ready.  
            View it here: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/${{ github.event_name == 'pull_request' && format('pr-{0}/allure-report', github.event.pull_request.number) || 'push/allure-report' }}
